spring.application.name=kafkabasic

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092}
spring.kafka.producer.value-serializer=JsonSerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.kafkabasic
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.kafkabasic.OrderEvent